### ISSUE TITLE
Explore and implement a way to grab 'Music in this video' section

### ISSUE THREAD

**Issue by parth-paradkar** [lttkgp/metadata-extractor#22]
YouTube generates a 'Music in this video' section for a lot of videos

![music-in-this-video](https://user-images.githubusercontent.com/45004153/93734654-baefe800-fbf7-11ea-998a-10658dc58e41.png)

This can be used to refine the parameters passed to Spotify further (album, artist, etc). Ways to get this section through the API or some other library can be explored.

**Comment by ghostwriternr** [comment]
Is this feature request different from what we already have? [scraper.py](https://github.com/lttkgp/metadata-extractor/blob/master/music_metadata_extractor/sources/youtube/scraper.py#L56-L64)

**Comment by thescriptninja** [comment]
When me and @cipherLord were testing this a while back, we found that that particular scraping code is failing for a lot of cases, due to some sort of inconsistency in the HTML tags on videos. We can look at other ways than scraping if it is possible.

Otherwise, we can look at testing the existing code further and covering all the cases.

**Comment by thescriptninja** [comment]
Youtube-DL has a way to do this apparently, might be much more cleaner and more consistent
https://stackoverflow.com/a/57231482

**Comment by cipherLord** [comment]
Has this issue been resolved? I might look into it otherwise. I have used YouTube-DL previously while making a discord bot.

**Comment by parth-paradkar** [comment]
I believe we can close this now. The YouTube API is working fine along with Spotify search. We can re-open if at all we face the need.
